name: Gerar cartões do perfil

on:
  workflow_dispatch:

  schedule:
    - cron: "0 4 * * *"

  push:
    branches:
      - main

jobs:
  gerar-cartoes:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Gerar cartões
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: -3
